### ISSUE TITLE
Problem with enum as parameter from underlying service

### ISSUE THREAD

**Issue by Vololodia** [cruisade/swaggelot#1]
I've met problem with enums as params of underlying service endpoints. For example underlying service have endpoint `~/api/v1/books` that accepts query params:
* editions (array of enum: `EditionType`)
* cover (enum: `CoverType`)

Swaggelot (swagger of Ocelot gateway) configured to reach that service endpoint. In Swagger UI we will see that `editions` accepts array with possible values from `EditionType` enum - that is valid behaviour. But `cover` accepts any string, ignoring related enum values (UI even doesn't suggest you any enum value) - that is invalid behaviour.

So actually it look like for some reason Swaggelot lost relation between enum and parameter, in case of parameter having enum type.

**Comment by cruisade** [comment]
fixed

**Comment by cruisade** [comment]
fixed
